// css
import 'cooltipz-css'
import './scss/variables.css'
import 'svelte-material-ui/bare.css'
import 'winbox/src/css/winbox.css'
// scss
import './scss/smui-theme-variables.scss'
import './scss/materialTheme.scss'
import './scss/bulma-style.scss'
import './scss/styles.scss'
import './scss/ck-editor.scss'
import './scss/toast.scss'